name = "rbfqr"
uuid = "cd2b1bcb-57b2-4da1-8704-3b60a61b5492"
authors = ["Fredrik Fryklund <ffry@kth.se>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
